apiVersion: v1
kind: Service
metadata:
  name: alertmanager-{{ .Values.node.name }}-service
spec:
  type: ClusterIP
  selector:
    alertmanager: monitoring-{{ .Values.node.name }}
  ports:
    - name: web
      protocol: TCP
      port: 9093
      targetPort: 9093
