apiVersion: v1
kind: Service
metadata:
  name: ipfs-{{ .Values.node.name }}-service
  labels:
    app.kubernetes.io/component: ipfs-{{ .Values.node.name }}-service
    app.kubernetes.io/name: ipfs-{{ .Values.node.name }}
    app.kubernetes.io/part-of: graph-indexer
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: ipfs-{{ .Values.node.name }}
  ports:
  - name: ipfs
    protocol: TCP
    port: 5001
