apiVersion: v1
kind: Service
metadata:
  name: prometheus-{{ .Values.node.name }}-service
spec:
  type: ClusterIP
  selector:
    prometheus: monitoring-{{ .Values.node.name }}
  ports:
    - name: web
      protocol: TCP
      port: 9090
      targetPort: 9090
