replicaCount: 1
imagePullPolicy: Always

image:
    name: bwrdevops/graph-node
    tag: v0.27.1

labels:
  project: graph-indexer

ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/whitelist-source-range: "0.0.0.0/0"

persistence:
  ## If true, use a Persistent Volume Claim, If false, use emptyDir
  enabled: true
  storageClass: "-"
  accessModes: ReadWriteOnce
  storage: 30Gi

nodeSelector: {}

tolerations: 
  - key: component
    value: graph-indexer	
    operator: Equal
    effect: NoSchedule

affinity: {}

chain: graph-indexer
environment: prod
network: mainnet

node:
  name: klaytn

CustomValues:
  chain_name: "klaytn"
  endpoint: "<URL>" # UPDATE THE VALUE
  postgress:
    external: true
    query:
      host: "<HOST>" # UPDATE THE VALUE
      username: "postgres" 
      password: "postgres"
      database: "graph"
      port: 5432
    indexer:
      host: "<HOST>" # UPDATE THE VALUE
      username: "postgres" 
      password: "postgres"
      database: "graph"
      port: 5432





    
